# Generated by Django 4.2.2 on 2023-06-21 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reply',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
