# Generated by Django 4.2.2 on 2023-06-22 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0003_alter_post_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='categories',
            new_name='category',
        ),
    ]
